/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.student_information_management_system;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Naveesha
 */
public class Course_Registration_Form extends javax.swing.JFrame {

    /**
     * Creates new form Course_Registration_Form
     */
    public Course_Registration_Form() {
        initComponents();
        connect();
    }
    Connection con;
    PreparedStatement pst;
    ResultSet rs;
    public void connect()
    {
        try {
            Class.forName("com.mysql.cj.jdbc.Driver");
            String connection_String="jdbc:mysql://localhost/student_management_system";
            String user_name="root";
            con=DriverManager.getConnection(connection_String,user_name,"");
        } 
        catch (ClassNotFoundException ex) {
            Logger.getLogger(Student_Registration.class.getName()).log(Level.SEVERE, null, ex);
        } 
        catch (SQLException ex) {
            Logger.getLogger(Student_Registration.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        btnbackLec = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtCourseID = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtCourseName = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtCourseRequirements = new javax.swing.JTextField();
        btnAddCourseRequirements = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        cbxCourseCategory = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        spnr_NoOfYearsOfCourse = new javax.swing.JSpinner();
        jLabel7 = new javax.swing.JLabel();
        spnr_NoOfMonthsOfCourse = new javax.swing.JSpinner();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txtCourseFee = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        cbx_Location = new javax.swing.JComboBox<>();
        btnRegisterCourse = new javax.swing.JButton();
        btnCancel = new javax.swing.JButton();
        btnbackCourse = new javax.swing.JButton();

        jButton1.setText("Add the Acadamic  Qualification");

        jButton3.setText("Register");

        jButton4.setText("Cancel");

        btnbackLec.setText("<<-Back");
        btnbackLec.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnbackLecActionPerformed(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setText("Add New  Course ");

        jLabel2.setText("Course ID");

        jLabel3.setText("Course Name");

        jLabel4.setText("Course Requirements");

        btnAddCourseRequirements.setText("Add Course Requirement");
        btnAddCourseRequirements.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddCourseRequirementsActionPerformed(evt);
            }
        });

        jLabel5.setText("Category");

        cbxCourseCategory.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Information Technology (IT)", "Engineering", "Business and Management", "Languages and Communication", "Design and Multimedia", "School Leavers’ Programs" }));

        jLabel6.setText("Duration");

        jLabel7.setText("Years");

        jLabel8.setText("Months");

        jLabel9.setText("Course Fee");

        jLabel10.setText("Location");

        cbx_Location.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Colombo", "Matara", "Galle" }));

        btnRegisterCourse.setText("Register");
        btnRegisterCourse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegisterCourseActionPerformed(evt);
            }
        });

        btnCancel.setText("Cancel");

        btnbackCourse.setText("<<-Back");
        btnbackCourse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnbackCourseActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(341, 341, 341)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addComponent(jLabel4)
                                        .addGap(18, 18, 18)
                                        .addComponent(txtCourseRequirements))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addComponent(jLabel5)
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(cbxCourseCategory, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                .addGroup(layout.createSequentialGroup()
                                                    .addComponent(jLabel8)
                                                    .addGap(18, 18, 18)
                                                    .addComponent(spnr_NoOfMonthsOfCourse, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGroup(layout.createSequentialGroup()
                                                    .addComponent(jLabel7)
                                                    .addGap(18, 18, 18)
                                                    .addComponent(spnr_NoOfYearsOfCourse, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                        .addGap(0, 256, Short.MAX_VALUE)))
                                .addGap(18, 18, 18)
                                .addComponent(btnAddCourseRequirements, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel3)
                                            .addComponent(jLabel2))
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(18, 18, 18)
                                                .addComponent(txtCourseName, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                .addGap(17, 17, 17)
                                                .addComponent(txtCourseID, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                    .addComponent(jLabel6)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel9)
                                        .addGap(18, 18, 18)
                                        .addComponent(txtCourseFee, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel10)
                                        .addGap(18, 18, 18)
                                        .addComponent(cbx_Location, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnbackCourse, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnRegisterCourse, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(57, 57, 57))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txtCourseID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtCourseName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(txtCourseRequirements, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnAddCourseRequirements)))
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(cbxCourseCategory, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel6)
                .addGap(2, 2, 2)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addComponent(spnr_NoOfYearsOfCourse, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8)
                    .addComponent(spnr_NoOfMonthsOfCourse, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(txtCourseFee, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbx_Location, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 152, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnRegisterCourse)
                    .addComponent(btnCancel)
                    .addComponent(btnbackCourse))
                .addGap(37, 37, 37))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAddCourseRequirementsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddCourseRequirementsActionPerformed
        if(txtCourseID.getText().isEmpty()||txtCourseRequirements.getText().isEmpty())
        {
            JOptionPane.showMessageDialog(this,"CourseID and Course Requirements fields needs to be filled");
        }
        else{
        try {
            // TODO add your handling code here:
            String courseRequirements=txtCourseRequirements.getText();
            String courseID=txtCourseID.getText();
            
            String CourseRequirement_addQuery="INSERT INTO courserequirementstable(courseID,courseRequirements) VALUES(?,?);";
            pst=con.prepareStatement(CourseRequirement_addQuery);
            
            pst.setString(1,courseID);
            pst.setString(2,courseRequirements);
            
            
            int x=pst.executeUpdate();
            if(x==1)
            {
                JOptionPane.showMessageDialog(this,"Course Requirements Added Successfully!!");
                
                txtCourseRequirements.setText("");
   
            }
            else
            {
                JOptionPane.showMessageDialog(this,"Course failed to saved!!");
            }
        } catch (SQLException ex) {
            Logger.getLogger(Course_Registration_Form.class.getName()).log(Level.SEVERE, null, ex);
        }
        }
    }//GEN-LAST:event_btnAddCourseRequirementsActionPerformed

    private void btnbackLecActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnbackLecActionPerformed
        // TODO add your handling code here:
        Admin_Main_Form Admin_Main_Form1=new Admin_Main_Form();
        Admin_Main_Form1.setVisible(true);
        // Optionally, close the current form
        this.dispose();
    }//GEN-LAST:event_btnbackLecActionPerformed

    private void btnbackCourseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnbackCourseActionPerformed
        // TODO add your handling code here:
        Course_Management_Form Course_Management_Form1=new Course_Management_Form();
        Course_Management_Form1.setVisible(true);
        // Optionally, close the current form
        this.dispose();
    }//GEN-LAST:event_btnbackCourseActionPerformed

    private void btnRegisterCourseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegisterCourseActionPerformed
        // TODO add your handling code here:
        if(txtCourseID.getText().isEmpty()||txtCourseName.getText().isEmpty()||cbxCourseCategory.getSelectedItem()==null||spnr_NoOfYearsOfCourse.equals("Select an option")||spnr_NoOfMonthsOfCourse.equals("Select an option")||txtCourseFee.getText().isEmpty()||cbx_Location.getSelectedItem()==null)
        {
            JOptionPane.showMessageDialog(this,"All fields needs to be validate");
        }
        else
        {
        try {
            
            String courseID=txtCourseID.getText();
            String courseName=txtCourseName.getText();
            String courseCategory=cbxCourseCategory.getSelectedItem().toString();
            int no_Of_years=(int)spnr_NoOfYearsOfCourse.getValue();
            int no_Of_months=(int)spnr_NoOfMonthsOfCourse.getValue();
            int CourseFee = Integer.parseInt(txtCourseFee.getText());
            String location=cbx_Location.getSelectedItem().toString();
            
            String Course_addQuery="INSERT INTO coursesdetails_table(courseID,course_Name,category,years,months,course_Fee,location) VALUES(?,?,?,?,?,?,?);";
            pst=con.prepareStatement(Course_addQuery);
            
            pst.setString(1,courseID);
            pst.setString(2,courseName);
            pst.setString(3,courseCategory);
            pst.setString(4,String.valueOf(no_Of_years));
            pst.setString(5,String.valueOf(no_Of_months));
            pst.setString(6,String.valueOf(CourseFee));
            pst.setString(7,location);
            
            int x=pst.executeUpdate();
            if(x==1)
            {
                JOptionPane.showMessageDialog(this,"Course Added Successfully!!");
                txtCourseID.setText("");
                txtCourseName.setText("");
                txtCourseRequirements.setText("");
                txtCourseFee.setText("");

                
                
            }
            else
            {
                JOptionPane.showMessageDialog(this,"Course failed to saved!!");
            }
        } catch (SQLException ex) {
            Logger.getLogger(Course_Registration_Form.class.getName()).log(Level.SEVERE, null, ex);
        }
        }
    }//GEN-LAST:event_btnRegisterCourseActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Course_Registration_Form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Course_Registration_Form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Course_Registration_Form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Course_Registration_Form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Course_Registration_Form().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddCourseRequirements;
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnRegisterCourse;
    private javax.swing.JButton btnbackCourse;
    private javax.swing.JButton btnbackLec;
    private javax.swing.JComboBox<String> cbxCourseCategory;
    private javax.swing.JComboBox<String> cbx_Location;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JSpinner spnr_NoOfMonthsOfCourse;
    private javax.swing.JSpinner spnr_NoOfYearsOfCourse;
    private javax.swing.JTextField txtCourseFee;
    private javax.swing.JTextField txtCourseID;
    private javax.swing.JTextField txtCourseName;
    private javax.swing.JTextField txtCourseRequirements;
    // End of variables declaration//GEN-END:variables
}
