/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.student_information_management_system;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Naveesha
 */
public class lecturer_Registration_Form extends javax.swing.JFrame {

    /**
     * Creates new form lecturer_Registration_Form
     */
    public lecturer_Registration_Form() {
        initComponents();
        connect();
        loadCourses();
    }
    Connection con;
    PreparedStatement pst;
    ResultSet rs;
    public void loadCourses()
    {
        String loadCourses_query="SELECT courseID FROM coursesdetails_table;";
        try {
            pst=con.prepareStatement(loadCourses_query);
            rs=pst.executeQuery();
            cbxCourses.removeAllItems();
            
            while(rs.next())
            {
                cbxCourses.addItem(rs.getString(1));
            }
        } 
        catch (SQLException ex) {
            Logger.getLogger(lecturer_Registration_Form.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    public void connect()
    {
        try {
            Class.forName("com.mysql.cj.jdbc.Driver");
            String connection_String="jdbc:mysql://localhost/student_management_system";
            String user_name="root";
            con=DriverManager.getConnection(connection_String,user_name,"");
        } 
        catch (ClassNotFoundException ex) {
            Logger.getLogger(lecturer_Registration_Form.class.getName()).log(Level.SEVERE, null, ex);
        } 
        catch (SQLException ex) {
            Logger.getLogger(lecturer_Registration_Form.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtLecFirstName = new javax.swing.JTextField();
        txtLecLastName = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtEmail = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtPhoneNumber = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtAcadamicQualification = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txtAddress = new javax.swing.JTextField();
        btnAddAcadamicQualification = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        cbx_ProfessionalExperienceType = new javax.swing.JComboBox<>();
        jLabel11 = new javax.swing.JLabel();
        spnr_NoOfYearsExperience = new javax.swing.JSpinner();
        btnAddProfessionalExperience = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        cbxCourses = new javax.swing.JComboBox<>();
        jLabel13 = new javax.swing.JLabel();
        cbxCourseModules = new javax.swing.JComboBox<>();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        txtEmployeeID = new javax.swing.JTextField();
        btnLecturerRegister = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        btnbackLec = new javax.swing.JButton();
        txtPassword = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setText("Lecturer Registration");

        jLabel2.setText("First Name");

        jLabel3.setText("Last Name");

        jLabel4.setText("Email");

        jLabel5.setText("Phone Number");

        jLabel6.setText("Full Name");

        jLabel7.setText("Contact Information");

        jLabel8.setText("Home Address");

        jLabel9.setText("Acadamic Qualifications");

        txtAddress.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAddressActionPerformed(evt);
            }
        });

        btnAddAcadamicQualification.setText("Add the Acadamic  Qualification");
        btnAddAcadamicQualification.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddAcadamicQualificationActionPerformed(evt);
            }
        });

        jLabel10.setText("Professional Experience type");

        cbx_ProfessionalExperienceType.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Teaching", "Industry" }));

        jLabel11.setText("Professional Experience (Years)");

        btnAddProfessionalExperience.setText("Add the Professional Experience");
        btnAddProfessionalExperience.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddProfessionalExperienceActionPerformed(evt);
            }
        });

        jLabel12.setText("Courses Taught");

        cbxCourses.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "CODSE", "CODCSD", "CODNE" }));

        jLabel13.setText("Course Module/s");

        cbxCourseModules.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "All", "ICS", "MC", "DL&CA", "OOP" }));

        jLabel14.setText("Employee ID Number");

        jLabel15.setText("Password");

        btnLecturerRegister.setText("Register");
        btnLecturerRegister.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLecturerRegisterActionPerformed(evt);
            }
        });

        jButton4.setText("Cancel");

        btnbackLec.setText("<<-Back");
        btnbackLec.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnbackLecActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(336, 336, 336))
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel13)
                        .addGap(18, 18, 18)
                        .addComponent(cbxCourseModules, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnbackLec, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnLecturerRegister, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addGap(22, 22, 22)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel5)
                                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel3)
                                            .addComponent(jLabel2))
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(40, 40, 40)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(txtLecLastName, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 424, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(txtLecFirstName, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 424, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                .addGap(49, 49, 49)
                                                .addComponent(txtPhoneNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 439, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(layout.createSequentialGroup()
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 325, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                                .addGap(0, 233, Short.MAX_VALUE)))
                        .addContainerGap(38, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel15)
                        .addGap(18, 18, 18)
                        .addComponent(txtPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 444, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel11)
                                .addGap(18, 18, 18)
                                .addComponent(spnr_NoOfYearsExperience, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel9)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtAcadamicQualification, javax.swing.GroupLayout.PREFERRED_SIZE, 424, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(30, 30, 30)
                                .addComponent(btnAddAcadamicQualification, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addGap(34, 34, 34)
                                .addComponent(txtAddress, javax.swing.GroupLayout.PREFERRED_SIZE, 452, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel12)
                                    .addGap(18, 18, 18)
                                    .addComponent(cbxCourses, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(btnAddProfessionalExperience, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel10)
                                        .addGap(18, 18, 18)
                                        .addComponent(cbx_ProfessionalExperienceType, javax.swing.GroupLayout.PREFERRED_SIZE, 414, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel14)
                                .addGap(18, 18, 18)
                                .addComponent(txtEmployeeID, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel6)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel3))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txtLecFirstName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txtLecLastName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(14, 14, 14)
                .addComponent(jLabel7)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtPhoneNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(txtEmployeeID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(txtPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jLabel8))
                    .addComponent(txtAddress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(txtAcadamicQualification, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAddAcadamicQualification))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(cbx_ProfessionalExperienceType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(spnr_NoOfYearsExperience, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnAddProfessionalExperience)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(cbxCourses, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(cbxCourseModules, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 122, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnLecturerRegister)
                    .addComponent(jButton4)
                    .addComponent(btnbackLec))
                .addGap(45, 45, 45))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtAddressActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAddressActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAddressActionPerformed

    private void btnbackLecActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnbackLecActionPerformed
        // TODO add your handling code here:
        lectures_Management_Form lectures_Management_Form1=new lectures_Management_Form();
        lectures_Management_Form1.setVisible(true);
        // Optionally, close the current form
        this.dispose();
    }//GEN-LAST:event_btnbackLecActionPerformed

    private void btnLecturerRegisterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLecturerRegisterActionPerformed
        // TODO add your handling code here:
            String firstName=txtLecFirstName.getText();
            String lastName=txtLecLastName.getText();;
            String email=txtEmail.getText();
            String phoneNumber=txtPhoneNumber.getText();
            String address=txtAddress.getText();
            String lectureCourse=cbxCourses.getSelectedItem().toString();
            String lecCourseModules=cbxCourseModules.getSelectedItem().toString();
            String EmployeeID=txtEmployeeID.getText();
            String password=txtPassword.getText();
            
            

            if (txtLecFirstName.getText().isEmpty() || txtLecLastName.getText().isEmpty() || txtEmail.getText().isEmpty() || txtPhoneNumber.getText().isEmpty() || txtAddress.getText().isEmpty() || cbxCourses==null || cbxCourseModules==null || txtPassword.getText().isEmpty()) {
                JOptionPane.showMessageDialog(null, "All fields are required!");
            } 
            else {
                
            
        
            
                try {
                    


                
                String lecturer_addQuery = "INSERT INTO lecture_table(FirstName, LastName, Email, PhoneNumber, Address, teachingCourse, CourseModule, EmployeeIDNumber, password) VALUES(?,?,?,?,?,?,?,?,?);";

                pst=con.prepareStatement(lecturer_addQuery);

                pst.setString(1,firstName);
                pst.setString(2,lastName);
                pst.setString(3,email);
                pst.setString(4,phoneNumber);
                pst.setString(5,address);
                pst.setString(6,lectureCourse);
                pst.setString(7,lecCourseModules);
                pst.setString(8,EmployeeID);
                pst.setString(9,password);

                int x=pst.executeUpdate();
                if(x==1)
                {
                    JOptionPane.showMessageDialog(this,"The Lecturer Register successfully Successfully!!");
                    txtLecFirstName.setText("");
                    txtLecLastName.setText("");
                    txtEmail.setText("");
                    txtPhoneNumber.setText("");
                    txtAddress.setText("");
                    txtEmployeeID.setText("");
                    txtPassword.setText("");
                    
                }
                else
                {
                    JOptionPane.showMessageDialog(this,"Record failed to saved!!");
                }
        } 
        catch (SQLException ex) {
            Logger.getLogger(lecturer_Registration_Form.class.getName()).log(Level.SEVERE, null, ex);
        }
        }
    }//GEN-LAST:event_btnLecturerRegisterActionPerformed

    private void btnAddAcadamicQualificationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddAcadamicQualificationActionPerformed
        // TODO add your handling code here:
            String EmployeeID=txtEmployeeID.getText();
            String Educationualification=txtAcadamicQualification.getText();

            if (txtEmployeeID.getText().isEmpty()||txtAcadamicQualification.getText().isEmpty()) {
                JOptionPane.showMessageDialog(null, "EmployeeID and AcadamicQualification fields are required!");
            } 
            else {
                
            
        
            
                try {
                    


                
                String lecturerAcadamicQualification_addQuery = "INSERT INTO lecqualification_table(lecture_ID,acadamic_Qualification) VALUES(?,?);";

                pst=con.prepareStatement(lecturerAcadamicQualification_addQuery);

                pst.setString(1,EmployeeID);
                pst.setString(2,Educationualification);



                int x=pst.executeUpdate();
                if(x==1)
                {
                    JOptionPane.showMessageDialog(this,"The LecturerQualification added successfully Successfully!!");
                    txtAcadamicQualification.setText("");

                    
                }
                else
                {
                    JOptionPane.showMessageDialog(this,"Record failed to saved!!");
                }
        } 
        catch (SQLException ex) {
            Logger.getLogger(lecturer_Registration_Form.class.getName()).log(Level.SEVERE, null, ex);
        }
        }
        
    }//GEN-LAST:event_btnAddAcadamicQualificationActionPerformed

    private void btnAddProfessionalExperienceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddProfessionalExperienceActionPerformed
        // TODO add your handling code here:
            String EmployeeID=txtEmployeeID.getText();
            String LecProfessionalExperienceType=cbx_ProfessionalExperienceType.getSelectedItem().toString();
            String noOfYearsOfExperience=spnr_NoOfYearsExperience.getValue().toString();

            if (txtEmployeeID.getText().isEmpty()||cbx_ProfessionalExperienceType==null||spnr_NoOfYearsExperience==null) {
                JOptionPane.showMessageDialog(null, "EmployeeID,ProfessionalExperienceType and NoOfYearsExperience fields are required!");
            } 
            else {
                
            
        
            
                try {
                    


                
                String lecturerAcadamicQualification_addQuery = "INSERT INTO lecprofessionalexperience_table(EmployeeID,LecProfessionalExperienceType,noOfYears) VALUES(?,?,?);";

                pst=con.prepareStatement(lecturerAcadamicQualification_addQuery);

                pst.setString(1,EmployeeID);
                pst.setString(2,LecProfessionalExperienceType);
                pst.setString(3,noOfYearsOfExperience);



                int x=pst.executeUpdate();
                if(x==1)
                {
                    JOptionPane.showMessageDialog(this,"The Lecturer Professional Experience added successfully Successfully!!");
                    txtAcadamicQualification.setText("");

                    
                }
                else
                {
                    JOptionPane.showMessageDialog(this,"Record failed to saved!!");
                }
        } 
        catch (SQLException ex) {
            Logger.getLogger(lecturer_Registration_Form.class.getName()).log(Level.SEVERE, null, ex);
        }
        }
        
        
    }//GEN-LAST:event_btnAddProfessionalExperienceActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(lecturer_Registration_Form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(lecturer_Registration_Form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(lecturer_Registration_Form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(lecturer_Registration_Form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new lecturer_Registration_Form().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddAcadamicQualification;
    private javax.swing.JButton btnAddProfessionalExperience;
    private javax.swing.JButton btnLecturerRegister;
    private javax.swing.JButton btnbackLec;
    private javax.swing.JComboBox<String> cbxCourseModules;
    private javax.swing.JComboBox<String> cbxCourses;
    private javax.swing.JComboBox<String> cbx_ProfessionalExperienceType;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JSpinner spnr_NoOfYearsExperience;
    private javax.swing.JTextField txtAcadamicQualification;
    private javax.swing.JTextField txtAddress;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtEmployeeID;
    private javax.swing.JTextField txtLecFirstName;
    private javax.swing.JTextField txtLecLastName;
    private javax.swing.JPasswordField txtPassword;
    private javax.swing.JTextField txtPhoneNumber;
    // End of variables declaration//GEN-END:variables
}
